before_script:
  - export _R_CHECK_CRAN_INCOMING_=FALSE
  - export _R_CHECK_FORCE_SUGGESTS_=TRUE

r-base:
  stage: test
  image: r-base
  script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends libcurl4-openssl-dev libssh2-1-dev libssl-dev git
    - Rscript -e 'install.packages(c("devtools", "roxygen2", "testthat", "covr"), repos = "https://cran.rstudio.com/")'
    - Rscript -e 'devtools::install_deps()'
    - Rscript -e 'devtools::check()'
    - Rscript -e 'covr::codecov(type = "all", quiet = FALSE)'
