image: conoria/alpine-r

variables:
  BUILD_FLAGS: "--no-build-vignettes --no-manual"

test:
  script:
    - R CMD build . ${BUILD_FLAGS}
    - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
    - R CMD check $(ls -1t *.tar.gz | head -n 1) ${BUILD_FLAGS} --as-cran
