before_script:
  - apk --no-cache upgrade
  - export _R_CHECK_CRAN_INCOMING_=FALSE
  - export _R_CHECK_FORCE_SUGGESTS_=TRUE

alpine-r:
  stage: test
  image: conoria/alpine-r
  script:
    - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
    - Rscript -e 'devtools::check()'
    - Rscript -e 'covr::package_coverage(type = "tests", quiet = FALSE)'
