#' @title Calculate daily Ontario crop heat units for a given canadaHCD station
#'
#' @description Adds a column containing CHUs to the end of a \code{\link{tibble}} generated by \code{\link{hcd_daily}}.
#'
#' @param datain A \code{tibble} containing the data to process
#' @param report character; a vector of units to report (\code{"chu"} and/or \code{"gdd"})
#' @param tbase numeric; a base temperature for GDD calculation
#'
#' @importFrom tibble add_column
#'
#' @export
#'
#' @author Conor I. Anderson
#'
#' @source \insertRef{omafra_staff_field_2011}{canadaHCDx}
#'
#' @examples
#'
#' # Calulcate daily CHU at New Glasgow, Ontario
#' ng <- hcd_daily(4656, 1981:2010)
#' chu(ng)
#' chu(ng, report = "gdd", tbase = 10)

chu <- function(datain, report = c("chu", "gdd"), tbase = 0) {
  if (!inherits(datain, "data.frame")) {
    stop("Input data must be a data frame.")
  }

  if (!(report %in% c("chu", "gdd"))) {
    stop("We can only calculate CHUs and GDDs. Please check your report argument.")
  }

  tmax <- datain$MaxTemp
  tmin <- datain$MinTemp
  dataout <- datain

  if ("chu" %in% report) {
    ymax <- (3.33 * (tmax - 10)) - (0.084 * (tmax - 10.0) ^ 2)
    ymax[which(ymax < 0)] <- 0
    ymin <- 1.8 * (tmin - 4.4)
    ymin[which(ymin < 0)] <- 0
    chu <- (ymax + ymin) / 2
    dataout <- add_column(dataout, CHU = chu)
  }

  if ("gdd" %in% report) {
    gdd <- (tmax + tmin) / 2 - tbase
    gdd[which(gdd < 0)] <- 0
    dataout <- add_column(dataout, GDD = gdd)
  }

  return(dataout)
}
