##' @title Calculate daily Ontario crop heat units for a given canadaHCD station
##'
##' @description Adds a column containing CHUs to the end of a \code{\link{tbl_df}} generated by \code{\link{hcd_daily}}.
##'
##' @param datain A \code{tbl_df} containing the data to process
##' @param report character; a vector of units to report (\code{"chu"} and/or \code{"gdd"})
##' @param tbase numeric; a base temperature for GDD calculation
##'
##' @importFrom tibble add_column
##'
##' @export
##'
##' @author Conor I. Anderson
##' 
##' @source http://www.omafra.gov.on.ca/english/crops/pub811/10using.htm
##'
##' @examples
##'
##' # Calulcate daily CHU at New Glasgow, Ontario
##' ng <- hcd_daily(4656, 1981:2010)
##' chu(ng)
##' chu(ng, report = "gdd", tbase = 10)
##'

chu <- function(datain, report = c("chu", "gdd"), tbase = 0) {
  if(!inherits(datain, "data.frame")) {
    stop("Input data must be a data frame")
  }
  
  if (length(which(report == "chu")) == 0 && length(which(report == "gdd")) == 0) {
    stop("We can only calculate CHUs and GDDs. Please check your report argument.")
  }
  
  tmax <- datain$MaxTemp
  tmin <- datain$MinTemp
  dataout <- datain
  
  
  if (length(which(report == "chu")) == 1) {
    chu <- NULL
    
    for (i in 1:nrow(datain)) {
      ymax = max(((3.33 * (tmax[i]-10)) - (0.084 * (tmax[i]-10.0)^2)),0)
      ymin = max((1.8 * (tmin[i] - 4.4)),0)
      chu <- c(chu, ((ymax + ymin)/2))
    }
    
    dataout <- add_column(dataout, CHU = chu)
  }
  
  if (length(which(report == "gdd")) == 1) {
    gdd <- (tmax + tmin)/2 - tbase
    gdd[which(gdd < 0)] <- 0
    dataout <- add_column(dataout, GDD = gdd)
  }
  
  return(dataout)
}